app:
  env: local
  key: zBqYyQrPNaIUsnRhsGtHLivjqiMjBVLS
  debug: true
  url: http://localhost:8080
  port: 8080
  log:
    level: info
    type: daily

db:
  type: mysql
  host: 192.168.21.57
  port: 61306
  username: root
  password: cnstrong
  database: go-devops-admin
  debug: 2

redis:
  host: 192.168.21.86
  port: 6379
  password:
  cache_db: 0
  main_db: 1

jwt:
  expire_time: 120
  max_refresh_time: 86400

verify:
  code:
    length: 6
    expire: 15

mail:
  host: localhost
  port: 1025
  username:
  password:
  from:
    address: go-devops-admin@example.com
    name: devops

sms:
  aliyun:
    ACCESS_ID:
    ACCESS_SECRET:
    SIGN_NAME:
    TEMPLATE_CODE: 